### ISSUE TITLE
Write result of `iter8 run --dry` to stdout

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#1131]
`iter8 run --dry` renders experiment.yaml without running the experiment. Use of `iter8 run --dry` is to see the experiment being generated; it may be easier for users if we (also) output to stdout. This would be behavior similar to other tools like `helm template`.

**Comment by sriumcp** [comment]
Perhaps the real issue is how quiet the whole `iter8 run --dry` execution is? Would it be sufficient if we simply log the message, `Created experiment.yaml file which contains the Iter8 experiment spec`. 
***
If we do print to stdout, I feel we must have a `--verbose`  mode which makes that happen, and not the regular mode.
