### ISSUE TITLE
Iter8 CLI `iter8 gen k8s` hardcodes `0.8` version

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8#1154]
When using a specific CLI version, e.g., 0.8.29, to run `iter8 gen k8s`, it outputs a job using the `iter8/iter8:0.8` image. This defeats the purpose of having minor versions. Minor version should be added to the image tag.

**Comment by sriumcp** [comment]
I believe you mean `patch` version instead of `minor` version above (but point taken).

**Comment by huang195** [comment]
That's correct!

**Comment by sriumcp** [comment]
Could you please try `iter8 gen k8s --set image="iter8/iter8:v0.8.29"` (you may need to escape the dot ... setting an image explicitly is already supported by k8s template).
***
We can close this issue once you confirm that image setting works for you.

**Comment by sriumcp** [comment]
The default behavior of `iter8 gen k8s` should be left as it is for the following reasons... 

1. Patch updates could occur due to bug fixes or security updates.
2. Users should be able to get these fixes automatically without having to change anything.
3. By keeping the `v0.8` image as the latest stable version of the form `v0.8.X`, we achieve the above.

Of course, developers might need to work with specific images (including images hosted in their docker hub accounts), and `--set image` enables this.
