### ISSUE TITLE
iter8 launch emits log output to stderr

### ISSUE THREAD

**Issue by starpit** [iter8-tools/iter8#1244]
**Describe the bug**
I think this is a convention bug: stderr should mostly be for errors. Atypically, it can be used for "alt mode" output, if stdout has useful information on its own.

As far as I can tell, `iter8 launch` has no stdout output, and emits the nice and useful log messages to stderr. This makes it difficult to consume the output in upstream tools/scripts, as normally one would expect only errors to show up on stderr. For example, in order to pipe the output to grep... I need to reroute 2>1.

**To Reproduce**
n/a

**Expected behavior**
`iter8 launch` should stream to stdout

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS
 - Output of the `iter8 version` command
> cmd.BuildInfo{Version:"v0.10.17", GitCommit:"bdd83284100ebff7dbd4ad21fccc93d10375f1bd", GoVersion:"go1.17.8"}

**Additional context**
n/a

**Comment by sriumcp** [comment]
This is an interesting and useful point.

Outputs from `iter8 launch` are handled by Iter8 logging (which in turn uses `logrus` under the covers). We should check if logrus provides a way to separate `stdout` and `stderr` outputs depending upon the log level.

**Comment by sriumcp** [comment]
The underlying issue is that `iter8` uses `iter8Logger` struct for two different purposes: 1) for logging diagnostic messages (which should really go to `stderr`), and 2) for printing experiment outcomes/status/application-related output which should go to `stdout`.

1. Logger struct is [here](https://github.com/iter8-tools/iter8/blob/f6fd255965e974f3312b1e45a17f8ed9b0a24813/base/log/log.go#L16)
2. Example use of logger for "logging" purpose [here](https://github.com/iter8-tools/iter8/blob/f6fd255965e974f3312b1e45a17f8ed9b0a24813/base/assess.go#L46). Most usage of iter8Logger in the code is for this purpose -- this should go to `stderr`
3. Example use of logger for "printing" purposes [here](https://github.com/iter8-tools/iter8/blob/f6fd255965e974f3312b1e45a17f8ed9b0a24813/base/experiment.go#L738) -- this should go to `stdout`

**Comment by sriumcp** [comment]
Potential solution. Similar to `iter8Logger`, create `iter8Printer`.

We want:
```go
func (l *Iter8Printer) Print(msg string) {
  fmt.Println(msg) // goes to stdout
  Logger.Info(msg) // goes to stderr
}
```

**Comment by sriumcp** [comment]
On second thought, @kalantar @Alan-Cha ...

The above logic is going to print messages twice on your console! Which takes us back to [this bug](#1243).

So, I don't think we want the above solution :) 

***

How about we simply start using `fmt.Println(msg)` in various parts of the code, and then reassess if we need anything fancy at a later stage.

**Comment by sriumcp** [comment]
You can always redirect both `stdout` and `stderr` to the same file as follows ... assuming you want to look at them together.

```shell
command1 >> log_file 2>&1
```

**Comment by sriumcp** [comment]
We will use `fmt.Println(msg)` for printing status, and `log` for logging diagnostic messages.
