### ISSUE TITLE
Use `go install` for Iter8

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1458]
Excerpt from #1448:

Use `go install` for Iter8. `go install` is a powerful command that supports multiple architectures, minor version prefixes, SHA/commit-id based install, as well as installations from PR branches, and `latest` already. This means, we don't need `binaries`, `homebrew`, and `GitHub action` for Iter8 install.

**Comment by sriumcp** [comment]
- [x] We will no longer create assets: https://github.com/iter8-tools/iter8/blob/8d70e30c87e365a7c9f61274c865cf1cc26c6cc1/.github/workflows/assets.yaml#L8
- [x] Wherever we use Iter8 GitHub action (e.g., https://github.com/iter8-tools/iter8/blob/8d70e30c87e365a7c9f61274c865cf1cc26c6cc1/.github/workflows/assets.yaml#L104), we change it so that we `go install` iter8. Specifically, instead of `- uses: iter8-tools/iter8@v0.13`, we simply do `-run: "go install github.com/iter8-tools/iter8@0.13"` -- this needs to happen in a few places in our CI, because we are using Iter8 GitHub Action in a few places in the CI.
- [x] Remove `action.yaml` that supports the Iter8 Github Action
- [x] Make changes to Iter8 CLI install section/descriptions everywhere in iter8.tools
- [x] We still want to tell users (in iter8.tools website) how to use Iter8 within *their* GitHub action workflow: so modify iter8.tools documentation to use `go install github.com/iter8-tools/iter8@0.13`
