### ISSUE TITLE
Reuse traffic controller config for ABn controller

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8#1462]
Excerpt from https://github.com/iter8-tools/iter8/issues/1448:

Ensure that ABn controller re-uses the same config struct/file as the traffic controller. This is a breaking change since for ABn since the config information it uses today is somewhat different. Installation of ABn will need to change accordingly. Also, it will use the `routemap` weights directly from the traffic controller as part of its lookup call, to support weighted routing.

**Comment by kalantar** [comment]
The ABn code has two parts. 

- A controller that watches change to applications and creates an in memory representation.
- A grpc service that responds to `Lookup`, `WriteMetric` and `GetApplication`

The goal of this issue is to use the traffic manager controller instead of the ABn controller. That is, rewrite the service to use the structures created by the traffic controller instead of the current controller.

**Comment by kalantar** [comment]
duplicate
