### ISSUE TITLE
Code duplication in handler task implmentations

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8#827]
**Is your feature request related to a **problem**? Please describe the **problem**.**
Writing handler task Run methods requires interpolating variables with values from winning versions and or secrets and or the experiment object.  This is done in two steps:  to create a map[string]interface{} of tags and the interpolation itself. _The first step of creating a list of tags is common in different tasks_. The interpolation is applied to different fields of the task `with` object.  

Existing examples of the creation of tags are: for [common/bash](https://github.com/iter8-tools/handler/blob/main/lib/common/bash.go#L51-L71) and [common/exec](https://github.com/iter8-tools/handler/blob/main/lib/common/exec.go#L35-L47).  These are not quite identical; one is a rewrite of the other. When creating new tasks (ex. common/http-request), it was found that the same code was being written again. 

It is desirable to eliminate code duplication.  An effort to do so was made. Logically such a common method belongs in the `base` package. However, all attempts to do this minor refactor resulted in import cycles between the ` base` and `experiment` packages.

**Describe the feature/solution you'd like**
It is desirable to eliminate code duplication. Write a `GetDefaultTags` method to do this. Logically such a method is common to all tasks and belongs in the `base` package. 

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
No

**Will this feature/solution bring new benefits for Iter8 developers? What are they?**
Reducing code duplication allows for more targeted testing and reduces the likelihood of making a mistake.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
This issue suffices.

**How will this feature be tested?**
- [] existing test cases should work

**How will this feature be documented?**
There is no need. The behavior of interpolation is already described. It may need to be moved (as new tasks are written) to be independent of any particular task.

**Additional context**
In principle, this should be a straightforward refactor. However, all initial attempts resulted in import cycles between the `b ase` and `experiment` packages. To address this, a more invasive refactor seems to be required.

**Comment by sriumcp** [comment]
> Attempts to do so resulted in import loops between packages base and experiment.

I don't think this issue is describing a bug in the current Iter8 handler codebase. Or is it? It seems to be describing a buggy attempt to solve some problem (avoiding code duplication).

Note that duplicated code, while not desirable, in and of itself  is not a bug.

If my reading above is correct, does it make sense to relabel this as an enhancement and not a bug? 

And reword the issue accordingly, so that the issue clearly describes the problem with *current* code base (which seems to be duplicated code?).

**Comment by sriumcp** [comment]
Go code will not compile if there are cyclic dependencies.

Currently, Iter8 handler compiles just fine.

So, I am at a bit of a loss with this statement:  "resulted in import loops between packages base and experiment"; this definitely cannot be an issue with the current code because it does compile.

My additional concern is that -- there are two files with some common code, and here is a PR to solve this problem that touches 28 files. I am wondering why?

**Comment by kalantar** [comment]
> I don't think this issue is describing a bug in the current Iter8 handler codebase. Or is it? 

I also didn't really know. I rewrote the description as a feature. Perhaps that works better.

**Comment by kalantar** [comment]
In the proposed PR, @huang195 states:

> from the PR itself and the linked issue, it's not clear to me what the "import cycles" you're referring to

Agreed. I made an effort to refactor by creating a method in the base package. It imports experiment so that it can find the values of variables for the version recommended for promotion (it reads the experiment from a context.Context. In turn, experiment.go imports base.

**Comment by sriumcp** [comment]
Done.
